# Sample Config File
# Copy this file in the root directory and rename if `_config.xml`
# Once it's done, from the terminal run `jekyll init ` to create you Gemfile.
# Finally run `bundle exec jekyll server` to start jekyll bundle.

title: Title
description: Description

# Build settings
defaults:
  - scope:
      path: "assets/images"
    values:
      image: true

sass:
  sass_dir: _scss
  style: compressed

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - bower_components
  - webpack.config.js
  - package.json
