
title: Highway by Anthodpnt
description: Highway is an light-weight JS Page Loader

# Build settings
defaults:
  - scope:
      path: "assets/images"
    values:
      image: true

sass:
  sass_dir: _scss
  style: compressed

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - bower_components
  - webpack.config.js
  - package.json
